[platformio]
src_dir = src
default_envs = deskbot_v2_n16r8

[env:deskbot_v2_n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	adafruit/Adafruit ST7735 and ST7789 Library@1.11.0
	adafruit/Adafruit GFX Library@1.12.6
	adafruit/Adafruit BusIO@1.17.4
